language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - sudo apt-get install -y bison autoconf gpref flex
  - wget ftp://icarus.com/pub/eda/verilog/snapshots/verilog-20141205.tar.gz
  - tar -zxf verilog-20141205.tar.gz
  - cd verilog-20141205 && ./configure && make && sudo make install

install:
  - "pip install ."
  - "pip install -r requirements.txt"

services:
  - rabbitmq

before_script: python worker.py

script: nosetests