language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - sudo apt-get install -y bison autoconf flex gperf
  - wget ftp://icarus.com/pub/eda/verilog/snapshots/verilog-20141205.tar.gz
  - tar -zxf verilog-20141205.tar.gz
  - cd verilog-20141205 && ./configure && make && sudo make install && cd ../
  - wget http://www.veripool.org/ftp/verilator-3.866.tgz
  - tar -zxf verilator-3.866.tgz
  - cd verilator-3.866 && ./configure && make && sudo make install && cd ../

install:
  - "pip install -r requirements.txt"

services:
  - rabbitmq

before_script: 
  - python worker.py &
  - sleep 1

script: nosetests
