language: python
python:
- '2.6'
- '2.7'
before_install:
- export PATH="$PATH:/home/travis/vendor/bin"
- ls
- if [ ! -d 'flex-2.5.39' ]; then wget http://garr.dl.sourceforge.net/project/flex/flex-2.5.39.tar.bz2
  && tar -jxf flex-2.5.39.tar.bz2 && cd flex-2.5.39 && ./configure --prefix=/home/travis/vendor
  && make && make install && cd ../; else cd flex-2.5.39 && make install && cd ../;
  fi
- if [ ! -d 'gperf-3.0.4' ]; then wget http://ftp.gnu.org/pub/gnu/gperf/gperf-3.0.4.tar.gz
  && tar -zxf gperf-3.0.4.tar.gz && cd gperf-3.0.4 && ./configure --prefix=/home/travis/vendor
  && make && make install && cd ../; else cd gperf-3.0.4 && make install && cd ../;
  fi
- if [ ! -d 'bison-3.0.2' ]; then wget ftp://ftp.gnu.org/gnu/bison/bison-3.0.2.tar.gz
  && tar -zxf bison-3.0.2.tar.gz && cd bison-3.0.2 && ./configure --prefix=/home/travis/vendor
  && make && make install && cd ../; else cd bison-3.0.2 && make install && cd ../;
  fi
- if [ ! -d 'autoconf-2.69' ]; then wget ftp://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
  && tar -zxf autoconf-2.69.tar.gz && cd autoconf-2.69 && ./configure --prefix=/home/travis/vendor
  && make && make install && cd ../; else cd autoconf-2.69 && make install && cd ../;
  fi
- if [ ! -d 'verilog-20141205' ]; then wget ftp://icarus.com/pub/eda/verilog/snapshots/verilog-20141205.tar.gz
  && tar -zxf verilog-20141205.tar.gz && cd verilog-20141205 && ./configure --prefix=/home/travis/vendor
  && make && make install && cd ../; else cd verilog-20141205 && make install && cd
  ../; fi
- if [ ! -d 'verilator-3.866' ]; then wget http://www.veripool.org/ftp/verilator-3.866.tgz
  && tar -zxf verilator-3.866.tgz && cd verilator-3.866 && ./configure --prefix=/home/travis/vendor
  && make && make install && cd ../; else cd verilator-3.866 && make install && cd
  ../; fi
install:
- pip install -r requirements.txt
services:
- rabbitmq
before_script:
- python worker.py &
- sleep 1
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: AUl5il3/k9myPlcNKyAVcoc4Oo15ehrxBf307Er58MrWYleAvj00NkLqkk3zXGiqR/R6IxBud/t6HWKAzSh9RE+y6aDK/lDR9ehns0wH6ygpHiP5bHJUAiooEtwozh0TLYyofUyZvbAwK4z6YQwfLBaO41JaR3/HfNxUgaLB7Is=
  app: ovide-core
  on:
    repo: omarayad1/ovide-core
